### ISSUE TITLE
Simplify Entity-type and Mutable Properties in Config

### ISSUE THREAD

**Issue by LePips** [CreateAPI/CreateAPI#100]
We currently have two config options for entity-type generation, `entities.isGeneratingStructs` and `entities.isMakingClassesFinal`. Instead of these two flags, we condense into an enum:
```yaml
entities:
  type: struct || class || finalClass
```

Still preserve `entities.entitiesGeneratedAsClasses` and `entities.entitiesGeneratedAsStructs` for now.

Additionally, there are two config options for property generation: `entities.isGeneratingMutableClassProperties` and `entities.isGeneratingMutableStructProperties`. Condense into a simple bool:
```yaml
entities:
  mutableProperties: true || false # default true
```

**Comment by liamnichols** [comment]
I thought the same thing with `struct`, `class` and `finalClass`! 👍 

Similar for `mutableProperties`, although I am not sure if they needed to be kept separate or not since you can use `entitiesGeneratedAsClasses` and `entitiesGeneratedAsStructs` to generate a mix. 

Would somebody want to keep `structs` mutable but classes immutable? I can kind of see it but it does seem pretty edge case... Maybe we could start 0.1 with `mutableProperties` and if people want greater flexibility, we could support both boolean or array of types:

```yaml
# All
mutableProperties: [struct, class] # or true
# Either
mutableProperties: [struct]
mutableProperties: [class]
# None
mutableProperties: [] # or false
```

--- 

Lets do your suggested refactor as part of 0.1 though! 

```swift
public var type: EntiyType = .struct

public var mutableProperties: Bool = true
```

**Comment by liamnichols** [comment]
So while working on this, a couple of other things came up:

- `finalClasses` (`isMakingClassesFinal`) should remain because while `type` might be `struct`, you could still be generating a class via `entitiesGeneratedAsClasses`. 
- `entitiesGeneratedAsClasses` and `entitiesGeneratedAsStructs` could instead be consolidated into a Dictionary where the key is the entity name and the value is the type. 

Therefore, I think something like this is better suited:

```yaml
entities:
  defaultType: struct
  finalClasses: true
  typeOverrides:
    Foo: class
    Bar: class
```

But I'm not 100% happy having to repeat `class` each time. But `entitiesWithOppositeTypes` sound horrible 😄 Maybe it also defeats the purpose of having an enum too.

**Comment by LePips** [comment]
Yeah it might seem annoying to list every override however I think it's a lot more clear and declarative for _what_ a type should be. I think we can still include the three enum options and that the override will be one of those three options as well:

```yaml
entities:
  defaultType: struct
  typeOverrides:
    Foo: finalClass
    Bar: class

# or

entities:
  defaultType: finalClass
  typeOverrides:
    Foo: struct
    Bar: class # will not be a final class, we override to just class
```
