### ISSUE TITLE
Sort Properties of Parameters

### ISSUE THREAD

**Issue by LePips** [CreateAPI/CreateAPI#149]
Allow sorting of the parameters from generated Parameter structs.

```yaml
paths:
  sortQueryParameters: true || false
```

---

However, the above title poses an ambiguous problem for whether it sorts the inlined or Parameter type properties. Additionally, taking a look at the mixture of config options `paths.inlineSimpleRequests`, `paths.inlineSimpleQueryParameters`, `paths.simpleQueryParametersThreshold` I think that these can be simplified to the following:

```yaml
paths:
   # default inline
  parameterType: inline || object
  # sorts all parameters
  sortParameters: true || false
  # options for defining an object parameter
  objectParameter: 
    # default false?
    inlineRequiredParameters: true || false
    # takes the first two parameters, *after* sorting if true
    inlineThreshold: 2
  parameterTypeOverrides:
    # use the operationID or eventually the JSON mapping names
    myOperation: inline
    myOtherOperation: object
```
