### ISSUE TITLE
`useSwiftyPropertyNames` and `sortPropertiesAlphabetically` ordering

### ISSUE THREAD

**Issue by LePips** [CreateAPI/CreateAPI#174]
Using `useSwiftyPropertyNames: true` and `entities.sortPropertiesAlphabetically: true`, the `is-` conversion is happening after the alphabetical sorting.

Example schema:

```yaml
// ...
components:
  schemas:
    Pet:
      title: A pet title
      description: A pet description
      type: object
      required:
        - id
      properties:
        id:
          type: string
        likesMeat:
          type: boolean
        allergic:
          type: boolean

```

Generates the following:

```swift
public struct Pet: Codable {
    public var isAllergic: Bool?
    public var id: String
    public var isLikesMeat: Bool?

    // ...
}
```

It would be much more preferable if properties were properly sorted:

```swift
public struct Pet: Codable {
    public var id: String
    public var isAllergic: Bool?
    public var isLikesMeat: Bool?

    // ...
}
```

Additionally, it would probably be beneficial for an exclude list for `useSwiftyPropertyNames` as some property conversions may not be grammatically preferable, like in the above example.
