### ISSUE TITLE
Entity Individual Property Swift Type Override

### ISSUE THREAD

**Issue by LePips** [CreateAPI/CreateAPI#176]
While property schema `datatype`'s can be overridden, I need to be able to override a single entity property type.

---

### Context

The schema I am using has a string property that is represented by a string enum on the backend however isn't specified in the schema as an enum due to the complexity/time of rewriting the backend using that enum (along with a few others).

So, I have my own Swift enum specified and would like to use that instead.

Currently the following would be generated:
```swift
struct MyItem {
	let itemType: String
}
```

What should come from generation:
```swift
struct MyItem {
	let itemType: MyItemType
}
```

---

### Implementation

Introduce new config option `entities.propertyTypeOverrides` which represents a mapping of scheme properties to Swift types,

```yaml
entities:
  propertyTypeOverrides:
    MyItem.itemType: MyItemType
```

This option would take precedence over the datatype override and would follow the same rule:

> It is your responsibility to ensure that the replacement type conforms to Codable and can properly decode and encode to the original primitive type.

**Comment by liamnichols** [comment]
Hi @LePips, sorry that it took so long to get around to responding here and thanks for opening up the proposal! 

Before looking deeper into this, is this something that could be similarly achieved by using a custom `format` value?

https://swagger.io/docs/specification/data-models/data-types/#format

`format` is an open type so you are able to use any value in the schema, even those that are not known to OpenAPI. So with this, could it be possible to annotate your schema with custom formats that represent different concepts and then provide a mapping via the existing `dataTypes` mappings? 

```yaml
dataTypes:
  string:
    concept-one: EnumRepresentingConceptOne
    concept-two: EnumRepresentingConceptTwo
```

Then in the schema:

```yaml
properties:
  conceptTwo:
    type: string
    format: concept-two
```
