### ISSUE TITLE
integer backed enums are stored as integer properties as opposed to enums

### ISSUE THREAD

**Issue by mgrider** [CreateAPI/CreateAPI#184]
The issue is that an OpenAPI definition containing something like:

```yaml
        enum_integer:
          type: integer
          format: int32
          enum:
            - 1
            - 2
```

...will result in code that looks like:

```Swift
    public var enumInteger: Int?
```

That example is from the unit tests: https://github.com/CreateAPI/CreateAPI/blob/0069e8b87e7ea1dd1dc508f271de7d3ddaa7eb0e/Tests/Support/Specs/edgecases.yaml#L1097-L1102

I would prefer/expect to see something more like:

```Swift
    public enum EnumInteger: Int, Codable {
        case _1 = 1
        case _2 = 2
    }
```

I'm assuming this was a choice, probably? But maybe there could be a flag for it or something?
