### ISSUE TITLE
All command line arguments that alter output should be configurable in config file

### ISSUE THREAD

**Issue by liamnichols** [CreateAPI/CreateAPI#47]
Currently, we have a very vast amount of configuration options that must be included in the **create-api.yaml** file, but we also have some other options that also alter how the tool generates the output code that must be passed via CLI args. This includes the following:

- `-s, --split` - Split output into separate files
- `--package <package>` - Generates a complete package with a given name
- `--module <module>` - Use the following name as a module name
- `--vendor <vendor>` - Enabled vendor-specific logic (supported values: "github") 
- `--generate <generate>` - Specifies what to generate (default: paths, entities)
- `--filename-template <filename-template>` - Example: "%0.generated.swift" will produce files with the following names: "Paths.generated.swift". (default: %0.swift) 
- `--entityname-template <entityname-template>` - Example: "%0Generated" will produce entities with the following names: "EntityGenerated". (default: %0) 

This means that there are two sources to dig through when altering configuration, which has the potential to cause confusion. It also makes it hard to invoke `create-api` from multiple different places without either copying the desired arguments or wrapping the invocation in a script. 

Firstly, I'd like to understand if there is a good reason that these options should be separate to the options in the configuration file? 

If we agree that isn't the case, I'd like to start making them available in the configuration instead. 

Unless there is a good reason to keep the arguments as overrides to configuration options, my suggestion would be to deprecate them now and remove them in a future release. Printing a warning when used until they are removed.

**Comment by liamnichols** [comment]
I guess that one question could be, how many different schemas are we generating per configuration? 

It might make sense to invoke the command against multiple schemas, changing only the Package name but reusing the same configuration? 

But if this is the case, I might be more inclined to look for a more generic way to accept config file overrides instead? 

If users were doing this, we'd find out during the deprecation window and would be able to decide accordingly then

**Comment by liamnichols** [comment]
I'm moving this up to 0.1.0 as I think it could be an important breaking change to get right. As it stands, I want to move the following:

Argument|Config
---|---
`--split`/`-s`|`isMergingSources`
`--package`|`mode` & `target`
`--module`|`mode` & `target`
`--generate`|`entities.isEnabled` & `paths.isEnabled`
`--filename-template`|`rename.files`
`--entityname-template`|`rename.entities`
`--vendor`|`vendor`

For example, the following invocation:

```bash
$ create-api generate schema.json --config .create-api.yml --package "OctoKit" --generate entities --filename-template "%0.generated.swift" --entityname-template "%0DTO" --vendor github 
```

Would become the following: 

```bash
$ create-api generate schema.json --config .create-api.yml
```

**.create-api.yml**
```yml
mode: package
target: OctoKit
vendor: github
isMergingSources: true
paths:
  isEnabled: false
rename:
  files: "%0.generated.swift"
  entities: "%0DTO"
  properties:
    foo: bar
```

I'm still undecided on the file/entity templates... They feel like they should be part of renaming, and and obvious thing to do would be to support either templating or individual renames across all different types of renames. But in the event that there was somebody who relied both on `--entityname-template` as well as `rename.entities...`, they'd not be able to do both anymore. It seems pretty unlikely though?

**Comment by LePips** [comment]
Supportive of everything changed so far. Per https://github.com/CreateAPI/CreateAPI/issues/60 with entities and paths having separate renaming options, I simply propose:
```yaml
entities:
  fileTemplate: "%0Model.swift"
paths:
  fileTemplate: "%0API.swift"
```

I think overall we can even move at least `rename.properties`, `rename.parameters`, `rename.entities`, and `rename.operations` into their respective sections:
```yaml
entities:
  fileTemplate: "%0Model.swift"
  renameEntities: ...
  renameProperties: ...
paths:
  fileTemplate: "%0API.swift"
  renameParameters: ...
  renameOperations: ...
```

This still leaves `rename.enumCases` and `rename.collectionElements` but I can't think of a good moving scheme for them.
