### ISSUE TITLE
Consider making `isInliningPropertiesFromReferencedSchemas` the default behaviour

### ISSUE THREAD

**Issue by liamnichols** [CreateAPI/CreateAPI#63]
# Background 

Context: https://github.com/CreateAPI/CreateAPI/pull/61#discussion_r931894606

When `isInliningPropertiesFromReferencedSchemas` is not enabled (the default), it generates an invalid `Encodable` implementation. But generally speaking, the nested objects seem to not be consistent with how other generators generate code and it leads me to think that it's not the right choice to be nesting entities. 

My proposal is that we remove the `isInliningPropertiesFromReferencedSchemas` option and make it's behaviour the default.

**Comment by kean** [comment]
I think it's a good idea to make this behavior the default. Looking at the example, I'm not sure if the `Pet` even needs to be generated in this case (assuming it's only ever used in `allOf` and never referenced as a separate entity).

**Comment by kean** [comment]
I would suggest keeping this option because there are generally three types of ways to address it: composition, inheritance, and inlining all properties. CreateAPI covers everything but inheritance right now.

One more thing CreateAPI could do is inlining, generate `Pet` as a protocol and add conformance to it to the types like `Dog`.

**Comment by LePips** [comment]
> not sure if the `Pet` even needs to be generated
> generate `Pet` as a protocol

I've just started reading OpenAPI to learn but it seems more safe to inline or protocol as an inheritance hierarchy cannot necessarily be assumed with `allOf`.

```yaml
# default: inline
parentObjectGeneration: entity || protocol || inline
# or specify per type.
# default: inline
- parentObjectGeneration
  - Pet: protocol
  - Human: entity
```
