### ISSUE TITLE
Generate servers description

### ISSUE THREAD

**Issue by kean** [CreateAPI/CreateAPI#68]
OpenAPI provides a way to specify [available servers](https://swagger.io/docs/specification/api-host-and-base-path/) and their respective URLs:

```yaml
servers:
  - url: https://api.example.com/v1
    description: Production server (uses live data)
  - url: https://sandbox-api.example.com:8443/v1
    description: Sandbox server (uses test data)
```

CreateAPI could (optionally) generate a list of available servers:

```swift
enum Servers {
    // Sandbox server (uses test data)
    static let sandbox = URL(string: "https://sandbox-api.example.com:8443/v1")
    // Production server (uses live data)
    static let production = URL(string: "https://api.example.com/v1")
}
```

Usage: 

```swift
import Get

func usage() {
    let client = APIClient(baseURL: Servers.sandbox)
}
```

This feature would be nice to have. But I'm not sure how to generate the name for the servers. There is no `name` property, only `description` that can contain arbitrary text.

**Comment by LePips** [comment]
I think it can automatically generate a (rather useless) name but then the user can create a mapping based on the host (not including port for YAML purposes),

```yaml
servers:
  - https://production.com:Production
  - http://staging.dev:Staging
```

**Comment by kean** [comment]
Right, maybe it's best to leave it out of the scope, just like authentication. I don't see how you can possibly generate anything useful without having a basic `name` field.

**Comment by LePips** [comment]
I think this would be possible with just a full mapping of the URL, template and all.
```yaml
servers:
  - production: "https://production.com"
  - developing: "https://{customerId}.developing.com"
```

OpenAPIKit gives us an extensive `URLTemplate` object which we can probably create an `enum` for each server and the variables are filled in as the associated values:

```swift
enum Servers {
	case production
	case developing(customerId: String)
	
	var url: URL? {
		...
		case .developing(let customerId):
			// replace the variables in a URLTemplate and use their built in `.url` construction
	}
}
```

The `ParallelDocumentParser` just needs the decoding:
```swift
var servers: Result<[OpenAPI.Server], Error>!
perform(in: group) {
    servers = Result(catching: { try container.decode([OpenAPI.Server].self, forKey: .servers) })
}
```

While there is no `name` feature which would be the best thing, we can just have the default be alphabetical. This default doesn't seem like an issue for me as users that would use this feature would manually create the mapping anyways to work with it.
