### ISSUE TITLE
Exclude for Individual Properties

### ISSUE THREAD

**Issue by LePips** [CreateAPI/CreateAPI#71]
I have a very large object definition that contains itself by reference on a single property. The generator will currently turn this object into a `class` when I need a `struct` for usage in my app (just strongly prefer value types in my case). In my specific case I can just ignore the property that is causing this issue entirely, as I have done previously with editing the config file.

With the following example, I can just ignore `best_friend`:
```yaml
    Pet:
      title: A pet title
      description: A pet description
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: integer
          format: int64
        name:
          example: "Buddy"
          type: string
        tag:
          type: string
        best_friend:
          $ref: "#/components/schemas/Pet"
          description: "Best friend of your pet!"
```

```yaml
entities:
  - excludeProperties: ["Pet.best_friend"]
```

Will create an expected `struct` with no `bestFriend` property.

This is more of a discussion if `excludeProperties` is a good config name and whether the analog `includeProperties` should be created. In both cases, I know that I would have to check against the existing `exclude/include` lists to see if the object should be included in the overall generation. I think an error should be thrown in cases where usage of these flags together don't make sense. Or, we can just ignore these and leave it up to the user to have a clean config file.

```yaml
entities:
  # file 1
  - include: ["some-other-object"]
  - excludeProperties: ["Pet.best_friend"] # Error as "Pet" is not included in generation
  
  # file 2
  - include: ["some-other-object"]
  - includeProperties: ["Pet.best_friend"] # Error as "Pet" is not included in generation
  
  # file 3
  - exclude: ["Pet"]
  - excludeProperties: ["Pet.best_friend"] # Error as "Pet" is not included in generation
  
  # file 4
  - exclude: ["Pet"]
  - includeProperties: ["Pet.best_friend"] # Error as "Pet" not included in generation
```

Or instead of a new flag we change the sections to:
```yaml
entities:
  exclude:
    - objects: [...]
    - properties: [...]
  include:
    - objects: [...]
    - properties: [...]
```

### Refactor Idea

A brainstormed refactor to `include/exclude` could be the following:
```yaml
entities:
  # file 1
  - include:
    - Pet: # generates the "Pet" object with only the following properties
      - properties:
        - id
        - name
    - Store: # generates the "Store" object with no properties as it is empty
      - properties: 
    - Error: ... # need some way to indicate "Error" object generation with all properties included?

  # file 2
  - exclude:
    - Pet: # generates the original "Pet" object but excludes the following properties
      - properties:
        - id
        - name
    - Store: # generates the original "Store" object with no properties as it is empty
      - properties: 
    - Error: ... # need some way to indicate the "Error" object should be excluded entirely?
```

This refactor seems expansive but I feel a lot more declarative instead of splitting among a few lists that have to be checked against one another.

I will implement whatever option if approved.

**Comment by liamnichols** [comment]
In general, you could make the `exclude`/`include` arrays accept both String elements as well as object elements allowing you to write something like this:

```yaml
exclude:
- Pet # String ("Pet")
- name: Store # Object (["name": "Store", "properties": ["id", "name"]])
  properties:
  - id
  - name
```

It would require that the type of `exclude` changes from `[String]` to an array of some enum with a custom decoder.

The JSON would be something like this:

```json
{
  "exclude": [
    "Pet",
    {
      "name": "Store",
      "properties": [
        "id",
        "name"
      ]
    }
  ]
}
```

That being said, this feels a little complex. Under your `# file 2` example, when you provide `Store` in excludes with no properties, I would have imagined that it did nothing because you told it to exclude no properties (it's like an empty excludes array).

If I'm being honest, given that CreateAPI already appropriately converts the type to a `class` to avoid the recursion caused by a value type containing itself, maybe this is something that would need working around locally instead if it's just about preferring use of `structs`? 

Could you instead rename `Pet` to `_Pet` and then write your own `Pet` struct that doesn't contain the problematic property and map to it? 

While CreateAPI offers customisations and excludes to opt out of generating some portions of the schema, it does need to be careful to ensure that it's generated types conform to the specification that it's generating against. For example, if `Pet` was used in request bodies (i.e `PUT /pet/{id}`), by ignoring the `best_friend` property, we'd be serialising an invalid payload that the server would likely reject. This is something that we want to avoid.

**Comment by LePips** [comment]
I guess I wanted to cover all the bases of:
1 - exclude an object entirely
2 - generate object declaration but exclude its properties
3 - generate object declaration but exclude some of its properties

and vice versa for include. So, _declaring_ `properties:` in the config but having it empty would fit the case for 2. I'll drop 2 entirely and focus on 1 and 3 since I can't make any defense for it.

> working around locally ... rename ...

I would think this would be great however this specific object has **150** properties... yeah. I'm on the Jellyfin team so it's a monolith of a system and this stuff will never change. I would also be able to do that if [expanded parameters](https://forums.swift.org/t/pitch-introduce-expanded-parameters/51885) got anywhere. I would also have to do this with at least one other object.

> it does need to be careful to ensure that it's generated types conform to the specification that it's generating against.

This makes sense, however I also claim that it is up to the developer to know the API they are using. For all my objects, all of these properties are optional (`nullable` in schema) so if they are `nil` they aren't even used in any API calls. Only with a manual override would that change.

> invalid payload

We currently fail even with excluded objects. The file is not generated as expected but other objects and API calls that reference the excluded schema object still expect the generated object. We still leave it up to the developer to know the API they are working with.

So, to work with this `exclude` behavior:
- Present an **Error** if an excluded object is used in other objects or API calls
- Present a **Warning** if an excluded property is not `nullable`
- Show nothing if an excluded property is `nullable`
- Show nothing if an excluded object is not used in other objects or API calls 

For the last two, we could just show warnings anyways but it might seem redundant as the developer _knows_ they are excluded and they are not _expected_ by the schema.

We can leave `include` out for now.

**Comment by liamnichols** [comment]
Yeah thats a good point. And I actually had another thought where this could be useful:

- https://github.com/CreateAPI/CreateAPI/issues/96

I.e to ignore generation of a property that has been deprecated in order to validate that you aren't using it and to suppress the warnings generated due to internal usage.

How about also considering how we handle `rename.properties`? Where we can either rename all properties, or rename properties for a given type:

```yaml
rename:
  properties:
    identifier: id
    User.guid: id
```

So using a similar dot notation syntax in `excludes`? Like this:

```yaml
entities:
  excludes:
  - User # ignore the entire User entity 
  - Pet.bestFriend # ignore just the bestFriend property of Pet
```

Could that work? 

One thing to keep in mind also is that I'd love to improve validation around these kind of properties by making sure that only valid values are contained within them. For example, if you include `Pet.bestFriend` in the config, but `bestFriend` was removed from the `Pet` schema after it had been removed/renamed/etc, a warning or error should ideally be produced telling us that the exclude was valid (and therefore ignored). It's just an idea that I had in my head before you raised this ticket anyway and I've not thought much about how you'd actually know that/make it efficient
