### ISSUE TITLE
Add official way to opt out of using Get

### ISSUE THREAD

**Issue by liamnichols** [CreateAPI/CreateAPI#84]
# Background 

- https://github.com/CreateAPI/CreateAPI/pull/82#discussion_r936948277

As it stands, to opt out of using Get, you must do three things:

1. Use `--module` mode
2. Update `paths.imports` to be an empty array
3. Provide your own `Request` shim 

While we believe that using CreateAPI with Get it the quickest and easiest option, we understand that not everybody is in a position to adopt Get. As a result, we need to provide a better way to disable use of the dependency. 

# Description  

I can think of three scenarios:

1. You want to use Get and you are happy with the default behaviour
2. Your networking client already defines it's own `Request` in a module that should be imported
3. You will build your networking client on top of the generated code and want a `Request` type generated for you 

I did at first think that we should just generate `Request` if you opted not to use Get, but this will put some people who already import a different module defining `Request` in a situation where they can't use the generated code. It might be that like Get, the `Request` type is used for manually crafted requests too so defining it inside the CreateAPI generated package might not be appropriate. 

Not sure how best to handle this...

**Comment by liamnichols** [comment]
To support all three scenarios, I was thinking that maybe we could do it via either an enum or two bools:

### Default Behaviour (using Get)

```yaml
paths:
  requestType: useGet
```

```yaml
paths:
  isUsingGet: true
  isGeneratingRequestType: false
```

### Use Different `Request`

```yaml
paths: 
  requestType: none
```

```yaml
paths:
  isUsingGet: false
  isGeneratingRequestType: false
  imports:
  - MyAPIClient
```

### Generate `Request`

```yaml
paths:
  requestType: generate
```

```yaml
paths:
  isUsingGet: false
  isGeneratingRequestType: true
```

---

Being honest, I'm not a fan of either of these approaches. And in fact, I'm wondering if we can combine this with improvements to how `imports` work since we already know we need some improvements in this area. 

Currently, `imports` is just an array of strings. But it would be powerful if imports could also describe package dependencies (i.e the source and the version requirement) so that we can generate the complete Package definition. Going one step further, we could also declare what types (or features?) package `provides` to infer if we need to figure it out ourself... 

For example:

```yaml
dependencies:
- module: CoreLocation
  in: entities # or [entities, paths]
- module: MyAPIKit
  url: https://github.com/MyName/MyAPIKit.git
  branch: main
  provides:
  - Request
```

This would be a powerful feature that can enable a lot:

1. We can infer if `Request` needs to be generated based on the presence of a `provides` + if the user opted out of Get.
2. We could also apply it to other default dependencies? Although I'm not sure if they make so much sense as they're all very small.
3. We could apply it to any type (i.e generated types) in theory.
4. It makes `--package` generation more powerful because you can define your own dependencies to be included
5. We can relatively easily transition from the old approach since it also works with system imports/imports that aren't tied to SPM.

So back to the original examples 

**Default Behaviour (using Get)**
```yaml
# No configuration needed
```

**Use Different `Request`**
```yaml
dependencies:
- module: MyAPIKIt
  url: https://github.com/MyName/MyAPIKit.git
  from: 1.0.0
  provides:
  - Request
```

**Generate `Request`**
```yaml
paths:
  isGeneratingRequestType: true
```

The logic for importing `Get` would then be something like this:

```swift
var dependencies: [Dependency] = // ...
if !dependencies.contains(where: { $0.provides.includes("Request") }) && !options.paths.isGeneratingRequest {
    dependencies.append(Dependency(
        module: "Get",
        in: [.paths],
        url: "https://github.com/kean/Get.git",
        from: "1.0.2",
        provides: ["Request"]
    ))
}
```

I think this could work... I'll open a separate ticket for it 😄 Feel like a 0.2.0 thing though
