### ISSUE TITLE
Support inclusion of custom package dependencies

### ISSUE THREAD

**Issue by liamnichols** [CreateAPI/CreateAPI#85]
# Background

While it's possible to define additional `import`'s in the generated paths or entities code, it is not yet possible to declare dependencies to those modules in the generated **Package.swift**.

When investigating how to give the user more control over importing Get (and I guess other default dependencies), it became a bit clearer that we needed a more powerful way to define which dependencies we want to use and what they bring to the generated code. 

Se notes here: https://github.com/CreateAPI/CreateAPI/issues/84#issuecomment-1205026288

Fundamentally, I believe that we need a way to declare custom dependencies, and with that:

- Where the dependency comes from and it's version requirements (if it needs to go into **Package.swift**)
- What the dependency provides (i.e the `Request` type)
- Where the custom dependency is required (i.e maybe it only needs improving into entities)

With this information, we'd able to do the following:

1. Merge the custom dependencies with required dependencies (i.e Get) where appropriate
2. Figure out which files need to import which module
3. Embed each dependency in **Package.swift**, including the custom ones

# Examples

### Previous Behaviour

For matching the previous behaviour, the following config:

```yaml
entities:
  imports:
  - CoreLocation
```

Would become this:

```yaml
dependencies: 
- module: CoreLocation
  importIn:
  - entities
```

We can deprecate the old options and automatically backfill them during a transition period.

### Package Dependencies

In the event that we also need to bring in a package to help with some additional customisations:

```yaml
entities:
  protocols: 
  - DataTransferObject
dependencies:
- module: DataTransferKit
  url: https://github.com/myorg/DataTransferKit.git
  from: "0.0.2" # need other options too, such as branch, revision, upToNextMinor etc
  importIn:
  - entities
```

This will both import `DataTransferKit` in generated entity files for the protocol conformance, and will also include the dependency in the generated Package.swift file.

### Overrides

Finally, being able to override the existing imports. For example, Get:

```yaml
dependencies:
- module: MyAPIKit
  url: https://github.com/myorg/MyAPIKit.git
  branch: main
  provides:
  - Request
```

Instead of using `importIn`, this tells CreateAPI that this dependency provides the given type which would allow it to replace built-in dependencies that provide that type (Get). 

Right now, the generator would just import `MyAPIKit` instead of `Get` in all Paths, but in the future we would have the potential to expand this to any type. For example:

```yaml
paths:
  overriddenResponses:
    MyEntity: GenericType
dependencies:
- module: MyUtilsKit
  path: ../MyUtilsKit
  provides:
  - GenericType
```

And the result would be that `MyUtilsKit` is then imported only in specific source files that reference `GenericType`. 

While this would be neat, I don't think this is a requested feature right now so I imagine that it would be out of scope to begin with. It just demonstrates how `provides` has the potential to be very flexible.

**Comment by LePips** [comment]
With my work from #135 and omitting the `importIn` functionality, I think we should keep `entites.import` and `paths.import` as they exist now. This comes from a config organization and construction perspective, where the `entities` and `paths` sections hold options that configure their respective sections (for the most part). This also would also break some convention we have right now, where each section may describe a property with a list (`entites.import` now) instead of a property that may describe a flag of where to go `importIn: entities/paths`.

**Comment by LePips** [comment]
Per the `provides` option, for the `Request` type specifically I think creating `paths.requestProvider` would be optimal to make the, well, provider of `Request` more explicit instead of hiding under a dependency import. I say this because it's probably the most important type that we need.

Per the other usage of provides, that could be a bit easy and wonder how it would work with https://github.com/CreateAPI/CreateAPI/issues/114 at a fine level.

**Comment by liamnichols** [comment]
Ok I think that's cool. You are right, It's not too much burden to manage the `imports` manually and I had also been thinking about how this ties in with my note at the bottom of #134. 

If we keep `dependencies` strictly relating to Swift Package dependencies, then we can group them all under the same namespace in the config options:

```yaml
paths:
  enabled: false
package:
  enabled: true
  name: my-package
  dependencies:
    # ...
```

WDYT of this approach? I haven't looked at your PR yet but I can get #134 adjusted and merged asap so you can base the new dependencies option on top of it if so? 

The one thing that I wonder about is using the term `enabled` to describe inclusion of a given type of generated content? Is `included` a better alternative? Alternatively we could have a separate option called `generate` that would have been more like the original `--generate` flag:

```yaml
module: MyAPIKit
generate: [entities, package]
entities:
  defaultType: class
package:
  name: my-api-kit
  dependencies:
    # ...
```
  
We can take this conversation over to #134 if you'd like?
